name: insightmirror-test

services:
  postgres:
    profiles:
      - disabled

  server:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DATABASE_URL: postgresql://postgres:sf5mxikWU6nBf8qmXZqU7q4yIdQJ5JP9@host.docker.internal:65435/insight_mirror_test
      COMPUTE_SERVICE_URL: http://compute:8000
    depends_on:
      postgres:
        condition: service_healthy
        required: false

  compute:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DATABASE_URL: postgresql://postgres:sf5mxikWU6nBf8qmXZqU7q4yIdQJ5JP9@host.docker.internal:65435/insight_mirror_test
    depends_on:
      postgres:
        condition: service_healthy
        required: false

  web:
    ports:
      - "${EPORT:-9001}:80"
